/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.ScrollPane;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import logica.Historial;
import logica.Matriz;

/**
 *
 * @author Allan
 */
public class VentanaResultados extends javax.swing.JFrame {

    Matriz info;
    Historial historial;
    int cont;
    public VentanaResultados(Matriz info,Historial historial,int contador) {
        initComponents();
        //setResizable(false);
        this.setLocationRelativeTo(null);
        this.info=info;
        this.historial=historial;
        cont = contador;
        Generar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scrollPG = new javax.swing.JScrollPane();
        panelG = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana de resultados");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(627, 645));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        scrollPG.setBackground(new java.awt.Color(255, 255, 255));
        scrollPG.setBorder(null);
        scrollPG.setPreferredSize(new java.awt.Dimension(471, 486));

        panelG.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelGLayout = new javax.swing.GroupLayout(panelG);
        panelG.setLayout(panelGLayout);
        panelGLayout.setHorizontalGroup(
            panelGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );
        panelGLayout.setVerticalGroup(
            panelGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        scrollPG.setViewportView(panelG);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("High Tower Text", 0, 18)); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Generar(){
        int x = 20;
        int y = 20;
        for(int k=0;k<historial.getInfo().size();k++)
        {
            JLabel operacion= new javax.swing.JLabel();
            
            for(int i=0;i<historial.getInfo().get(k).getAlto();i++)
            {
                for (int j=0;j<historial.getInfo().get(k).getAncho();j++)
                {
                    JLabel T1,T2,lab;
                    T1 = new javax.swing.JLabel();
                    T2 = new javax.swing.JLabel();
                    lab=new javax.swing.JLabel();
                    operacion= new javax.swing.JLabel();
                    if(historial.getInfo().get(k).getMat().get(i).get(j).getDenominador()!=1){//si el denominador de la posicion es 1, no lo muestra
                        T2.setText(String.valueOf(historial.getInfo().get(k).getMat().get(i).get(j).getDenominador()));
                        lab.setText("___");
                    }
                    int tamanoMatriz = historial.getInfo().get(k).getAlto();
                    T1.setText(String.valueOf(historial.getInfo().get(k).getMat().get(i).get(j).getNumerador()));
                    /*this.panelG.add(T1, new org.netbeans.lib.awtextra.AbsoluteConstraints((j*80)+23, k*(tamanoMatriz*80+30)+(i*80)+50, 30, 30));
                    this.panelG.add(T2, new org.netbeans.lib.awtextra.AbsoluteConstraints((j*80)+23, k*(tamanoMatriz*80+30)+(i*80)+82, 30, 30));
                    this.panelG.add(lab, new org.netbeans.lib.awtextra.AbsoluteConstraints((j*80)+18, k*(tamanoMatriz*80+30)+(i*80)+67, 40, -1));*/
                    
                    T1.setLocation(x, y);
                    T1.setLayout(new GridLayout(1,2));
                    T1.setSize(40, 20);
                    lab.setLocation(x, y+3);
                    lab.setLayout(new GridLayout(1,2));
                    lab.setSize(40, 20);
                    T2.setLocation(x, y+17);
                    T2.setLayout(new GridLayout(1,2));
                    T2.setSize(40, 20);
                    
                    panelG.add(T1);
                    panelG.add(lab);
                    panelG.add(T2);
                    
                    x+=40;
                }
                x=20;
                y+=40;
                panelG.setPreferredSize(new Dimension(150,y+20));
            }
            x=20;
            y+=70;
            if(k < historial.getInfo().size()-1){
                operacion.setText("Operacion: "+historial.getPasos().get(k));
                int tamanoMatriz = historial.getInfo().get(k).getAlto();
                //this.panelG.add(operacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, (k+1)*(tamanoMatriz*80+30), 200, 30));
                operacion.setLocation(x, y-70);
                operacion.setLayout(new GridLayout(1,2));
                operacion.setSize(200, 30);
                panelG.add(operacion);
            }
            JLabel separar = new JLabel("\n*************************************\n"); 
            separar.setLocation(x, y-50);
            separar.setLayout(new GridLayout(1,2));
            separar.setSize(400, 30);
            panelG.add(separar);
        }
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VentanaOperaciones ventana = new VentanaOperaciones(info,historial);
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelG;
    private javax.swing.JScrollPane scrollPG;
    // End of variables declaration//GEN-END:variables
}
